apiVersion: server.eidolonai.com/v1alpha1
kind: Agent
metadata:
  name: repo-search

spec:
  implementation: RetrieverAgent
  name: "example_search"
  description: "Search the Eidolon github repository for code, examples, and documentation"
  document_manager:
    implementation: DocumentManager
    name: "example_search"
    loader:
      implementation: GitHubLoaderV2
      url: "https://github.com/eidolon-ai/eidolon.git"
      pattern:
        - "**/*.md"
        - "**/*.py"
      exclude: "**/test/**/*"
